#! /usr/bin/env bun
/**
 * VitePress's build fails on a link to a missing page but never checks the `#anchor` part
 * (its dead-link check strips `[?#].*` before recording the link), so a renamed heading
 * silently breaks every link to it.
 */
import { existsSync, globSync, readFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { createMarkdownRenderer, type MarkdownRenderer } from 'vitepress';

const repoRoot = resolve(import.meta.dir, '../..');
const siteDir = resolve(import.meta.dir, '../docs.warp-drive.io');

/** repo directory behind each top-level site path, per prepare-website.ts; `/api/` is generated by typedoc */
const siteRoots: Record<string, string> = {
  guides: 'guides',
  upgrading: 'upgrading',
  blog: 'blog',
  rfcs: 'rfcs',
  skills: 'warp-drive-packages/memory-alpha/skills',
};

type Token = ReturnType<MarkdownRenderer['parse']>[number];

interface Link {
  line: number;
  href: string;
}

interface Page {
  anchors: Set<string>;
  links: Link[];
}

interface Problem {
  file: string;
  line: number;
  href: string;
  reason: 'missing page' | 'missing anchor';
}

/** markdown-it passes raw HTML through as text, so its attributes are the one thing left to scan */
const htmlAttrPattern = /\s(id|src|href)="([^"]+)"/g;

/** `lines` is the frontmatter-stripped source that block maps index into; `offset` restores file line numbers */
function readPage(tokens: Token[], lines: string[], offset: number): Page {
  const page: Page = { anchors: new Set(), links: [] };
  function lineOf(block: Token, href: string): number {
    const [start, end] = block.map ?? [0, 1];
    const found = lines.slice(start, end).findIndex((line) => line.includes(href));
    return (found === -1 ? start : start + found) + 1 + offset;
  }
  function visit(token: Token, block: Token): void {
    const id = token.attrGet('id');
    if (id) page.anchors.add(id);
    const href = token.attrGet('href') ?? token.attrGet('src');
    if (href) {
      const decoded = decodeURIComponent(href);
      page.links.push({ line: lineOf(block, decoded), href: decoded });
    }
    if (token.type === 'html_block' || token.type === 'html_inline') {
      for (const [, name, value] of token.content.matchAll(htmlAttrPattern)) {
        if (name === 'id') page.anchors.add(value);
        else page.links.push({ line: lineOf(block, value), href: value });
      }
    }
    for (const child of token.children ?? []) visit(child, block);
  }
  for (const token of tokens) visit(token, token);
  return page;
}

/** pages keyed by repo-relative path, e.g. `guides/index.md` */
async function loadPages(): Promise<Map<string, Page>> {
  // shiki warns about every code fence whose language it does not know; that noise is not a link problem
  const md = await createMarkdownRenderer(siteDir, undefined, undefined, { warn() {} });
  const pages = new Map<string, Page>();
  for (const root of ['guides', 'upgrading', 'blog']) {
    for (const file of globSync('**/*.md', { cwd: join(repoRoot, root) })) {
      const path = join(root, file);
      const source = readFileSync(join(repoRoot, path), 'utf8');
      const env: { content?: string } = { path: join(repoRoot, path), relativePath: path, cleanUrls: false };
      const tokens = md.parse(source, env);
      const lines = (env.content ?? source).split('\n');
      pages.set(path, readPage(tokens, lines, source.split('\n').length - lines.length));
    }
  }
  return pages;
}

function isOutOfScope(href: string): boolean {
  return /^(https?:|mailto:|data:|\/api\/)/.test(href);
}

function resolveTarget(fromFile: string, target: string): string | undefined {
  let base: string;
  if (target.startsWith('/')) {
    const [, site, ...rest] = target.split('/');
    const root = siteRoots[site];
    if (root === undefined) return undefined;
    base = join(repoRoot, root, ...rest);
  } else {
    base = join(repoRoot, dirname(fromFile), target);
  }
  const withoutHtml = base.replace(/\.html$/, '');
  const candidates = [base, `${withoutHtml}.md`, join(withoutHtml, 'index.md')];
  const found = candidates.find((candidate) => existsSync(candidate));
  return found === undefined ? undefined : relative(repoRoot, found);
}

function findProblems(pages: Map<string, Page>): Problem[] {
  const problems: Problem[] = [];
  for (const [file, page] of pages) {
    for (const { line, href } of page.links) {
      if (isOutOfScope(href)) continue;
      const [target, anchor] = href.split('#');
      let destinationAnchors: Set<string> | undefined = page.anchors;
      if (target) {
        const resolved = resolveTarget(file, target);
        if (resolved === undefined) {
          problems.push({ file, line, href, reason: 'missing page' });
          continue;
        }
        destinationAnchors = pages.get(resolved)?.anchors;
      }
      if (anchor && destinationAnchors && !destinationAnchors.has(anchor)) {
        problems.push({ file, line, href, reason: 'missing anchor' });
      }
    }
  }
  return problems;
}

const pages = await loadPages();
const problems = findProblems(pages);
for (const { file, line, href, reason } of problems) {
  console.log(`${file}:${line}\t${reason}\t${href}`);
}
console.log(`checked ${pages.size} pages, ${problems.length} broken link(s)`);
process.exit(problems.length === 0 ? 0 : 1);
