#!/usr/bin/env node
/**
 * VitePress's build fails on a link to a missing page but never checks the `#anchor` part
 * (its dead-link check strips `[?#].*` before recording the link), so a renamed heading
 * silently breaks every link to it.
 *
 * Checks every content root that prepare-website.ts syncs into the site (see `siteRoots`),
 * including the memory-alpha skills, whose links otherwise go unverified.
 *
 * Links in a `::: tip <title>` container title are checked too. VitePress renders that title
 * with `md.renderInline` and a fresh `env` when it renders the page, so neither the parsed tokens
 * of the page nor VitePress's own dead-link check (which collects links into the page's `env`)
 * ever sees them.
 *
 * `--api` also checks the API pages that the docs build generates into `docs.warp-drive.io/api/`,
 * and every `/api/` link, so run it after a build. Without it, `/api/` links are skipped, since
 * those pages don't exist until TypeDoc has run.
 *
 * `--root <dir>` checks the content roots under `<dir>` instead of this repo's; the specs use it
 * to point the checker at a fixture tree.
 */
import { existsSync, globSync, readFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { createMarkdownRenderer, type MarkdownRenderer } from 'vitepress';

const { values: args } = parseArgs({ options: { root: { type: 'string' }, api: { type: 'boolean' } } });
const repoRoot = args.root ? resolve(args.root) : resolve(import.meta.dirname, '../..');
const siteDir = resolve(import.meta.dirname, '../docs.warp-drive.io');

/** repo directory behind each top-level site path, per prepare-website.ts; `/api/` is generated by the docs build */
const siteRoots: Record<string, string> = {
  guides: 'guides',
  upgrading: 'upgrading',
  blog: 'blog',
  rfcs: 'rfcs',
  skills: 'warp-drive-packages/memory-alpha/skills',
};
if (args.api) siteRoots.api = 'docs-viewer/docs.warp-drive.io/api';
/** repo directory VitePress serves as-is at the site root, for images and other static files */
const publicDir = 'docs-viewer/docs.warp-drive.io/public';

type Token = ReturnType<MarkdownRenderer['parse']>[number];

interface Link {
  line: number;
  href: string;
  /** for a markdown link, the `#anchor` VitePress renders it with, which can differ from `href`'s */
  anchor?: string;
}

interface Page {
  anchors: Set<string>;
  links: Link[];
}

interface Problem {
  file: string;
  line: number;
  href: string;
  reason: 'missing page' | 'missing anchor';
}

/** markdown-it passes raw HTML through as text, so its attributes are the one thing left to scan */
const htmlAttrPattern = /\s(id|src|href)="([^"]+)"/g;

/**
 * The inline tokens of a `::: <name> <title>` container's title, parsed the way VitePress's
 * container plugin renders it: `::: <name>` opens the block as a `container_<name>_open` token
 * with everything after `:::` in `info`, and the title is whatever follows the name.
 */
function containerTitleTokens(token: Token, md: MarkdownRenderer, env: object): Token[] {
  if (token.nesting !== 1 || !token.type.startsWith('container_')) return [];
  const name = token.type.slice('container_'.length, -'_open'.length);
  const title = token.info.trim().slice(name.length).trim();
  return title ? md.parseInline(title, env) : [];
}

/** `lines` is the frontmatter-stripped source that block maps index into; `offset` restores file line numbers */
function readPage(tokens: Token[], lines: string[], offset: number, md: MarkdownRenderer, env: object): Page {
  const page: Page = { anchors: new Set(), links: [] };
  /**
   * VitePress's link renderer rewrites a markdown link's `#anchor` to the slug of the heading it
   * names, so `#_defaultContentType` renders as `#defaultcontenttype`. Render the link the same way
   * and read the anchor back, rather than reimplementing its slugify.
   */
  function renderedAnchor(link: Token): string | undefined {
    md.renderer.renderInline([link], md.options, env);
    return link.attrGet('href')?.split('#')[1];
  }
  function lineOf(block: Token, href: string): number {
    const [start, end] = block.map ?? [0, 1];
    const found = lines.slice(start, end).findIndex((line) => line.includes(href));
    return (found === -1 ? start : start + found) + 1 + offset;
  }
  function visit(token: Token, block: Token): void {
    const id = token.attrGet('id');
    if (id) page.anchors.add(id);
    const href = token.attrGet('href') ?? token.attrGet('src');
    if (href) {
      const decoded = decodeURIComponent(href);
      const link: Link = { line: lineOf(block, decoded), href: decoded };
      if (token.type === 'link_open') link.anchor = renderedAnchor(token);
      page.links.push(link);
    }
    if (token.type === 'html_block' || token.type === 'html_inline') {
      for (const [, name, value] of token.content.matchAll(htmlAttrPattern)) {
        if (name === 'id') page.anchors.add(value);
        else page.links.push({ line: lineOf(block, value), href: value });
      }
    }
    for (const child of token.children ?? []) visit(child, block);
    for (const titleToken of containerTitleTokens(token, md, env)) visit(titleToken, block);
  }
  for (const token of tokens) visit(token, token);
  return page;
}

/** pages keyed by repo-relative path, e.g. `guides/index.md` */
async function loadPages(): Promise<Map<string, Page>> {
  // shiki warns about every code fence whose language it does not know; that noise is not a link problem
  const md = await createMarkdownRenderer(siteDir, undefined, undefined, { warn() {} });
  const pages = new Map<string, Page>();
  for (const root of Object.values(siteRoots)) {
    for (const file of globSync('**/*.md', { cwd: join(repoRoot, root) })) {
      const path = join(root, file);
      const source = readFileSync(join(repoRoot, path), 'utf8');
      const env: { path: string; relativePath: string; cleanUrls: boolean; content?: string } = {
        path: join(repoRoot, path),
        relativePath: path,
        cleanUrls: false,
      };
      const tokens = md.parse(source, env);
      const lines = (env.content ?? source).split('\n');
      pages.set(path, readPage(tokens, lines, source.split('\n').length - lines.length, md, env));
    }
  }
  return pages;
}

function isOutOfScope(href: string): boolean {
  return /^(https?:|mailto:|data:)/.test(href) || (!args.api && href.startsWith('/api/'));
}

function resolveTarget(fromFile: string, target: string): string | undefined {
  let base: string;
  if (target.startsWith('/')) {
    const [, site, ...rest] = target.split('/');
    const root = siteRoots[site];
    // any other root-relative path is a file VitePress serves from its public directory
    base = root === undefined ? join(repoRoot, publicDir, site, ...rest) : join(repoRoot, root, ...rest);
  } else {
    base = join(repoRoot, dirname(fromFile), target);
  }
  const withoutHtml = base.replace(/\.html$/, '');
  const candidates = [base, `${withoutHtml}.md`, join(withoutHtml, 'index.md')];
  const found = candidates.find((candidate) => existsSync(candidate));
  return found === undefined ? undefined : relative(repoRoot, found);
}

function findProblems(pages: Map<string, Page>): Problem[] {
  const problems: Problem[] = [];
  for (const [file, page] of pages) {
    for (const { line, href, ...link } of page.links) {
      if (isOutOfScope(href)) continue;
      const [target, hrefAnchor] = href.split('#');
      const anchor = link.anchor ?? hrefAnchor;
      let destinationAnchors: Set<string> | undefined = page.anchors;
      if (target) {
        const resolved = resolveTarget(file, target);
        if (resolved === undefined) {
          problems.push({ file, line, href, reason: 'missing page' });
          continue;
        }
        destinationAnchors = pages.get(resolved)?.anchors;
      }
      if (anchor && destinationAnchors && !destinationAnchors.has(anchor)) {
        problems.push({ file, line, href, reason: 'missing anchor' });
      }
    }
  }
  return problems;
}

const pages = await loadPages();
const problems = findProblems(pages);
for (const { file, line, href, reason } of problems) {
  console.log(`${file}:${line}\t${reason}\t${href}`);
}
console.log(`checked ${pages.size} pages, ${problems.length} broken link(s)`);
process.exit(problems.length === 0 ? 0 : 1);
