/**
 * @module
 * @summary Helpers `GET`, `POST`, `PUT`, `PATCH`, `DELETE` and `HEAD` that register a mocked request and its response
 * with the Holodeck test server, plus the scaffold types they accept.
 */

import { mock } from '.';

/**
 * @summary Full description of a mocked request, its request body to match, and its response status, headers, and body,
 * as sent to the Holodeck server to record a fixture.
 * @public
 */
export interface Scaffold {
  status: number;
  statusText?: string;
  headers: Record<string, string>;
  body: Record<string, string> | string | null;
  method: string;
  url: string;
  response: Record<string, unknown>;
}

/**
 * @summary Function that builds a complete mock scaffold, accepted by `mock` in place of a `LazyScaffold`.
 * @public
 */
export type ScaffoldGenerator = () => Scaffold;

/**
 * A mock whose method and url are known up front, with the rest of the
 * scaffold built only when holodeck is recording. This is what the mock
 * helpers pass, so that in replay mode a test's response generators never
 * run.
 *
 * @summary Mock whose method and url are known up front and whose full scaffold is built only when recording, as passed
 * by the Holodeck mock helpers to `mock`.
 * @public
 */
export interface LazyScaffold {
  method: string;
  url: string;
  scaffold: () => Scaffold;
}

/**
 * @summary Function passed to the Holodeck mock helpers that builds the response body, called only when recording a
 * fixture.
 * @public
 */
export type ResponseGenerator = () => Record<string, unknown>;

/**
 * Sets up Mocking for a GET request on the mock server
 * for the supplied url.
 *
 * The response body is generated by the supplied response function.
 *
 * Available options:
 * - status: the status code to return (default: 200)
 * - headers: the headers to return (default: {})
 * - body: the body to match against for the request (default: null)
 * - RECORD: record this request even when the suite is replaying, such as under CI (default: false).
 *   A local override for re-recording one request. Do not commit it; a committed RECORD means
 *   that request is never replayed against its fixture.
 *
 * @summary Mocks a GET request to a url on the Holodeck server, returning a generated response with a default 200
 * status.
 * @param url the url to mock, relative to the mock server host (e.g. `users/1`)
 * @param response a function which generates the response to return
 * @param options status, headers for the response, body to match against for the request, and whether to force recording
 * @return
 */
export function GET(
  owner: object,
  url: string,
  response: ResponseGenerator,
  options?: Partial<Omit<Scaffold, 'response' | 'url' | 'method'>> & { RECORD?: boolean }
): Promise<void> {
  return mock(
    owner,
    {
      method: 'GET',
      url,
      scaffold: () => ({
        status: options?.status ?? 200,
        statusText: options?.statusText ?? 'OK',
        headers: options?.headers ?? {},
        body: options?.body ?? null,
        method: 'GET',
        url,
        response: response(),
      }),
    },
    options?.RECORD
  );
}

const STATUS_TEXT_FOR = new Map([
  [200, 'OK'],
  [201, 'Created'],
  [202, 'Accepted'],
  [203, 'Non-Authoritative Information'],
  [204, 'No Content'],
  [205, 'Reset Content'],
  [206, 'Partial Content'],
  [207, 'Multi-Status'],
  [208, 'Already Reported'],
  [226, 'IM Used'],
  [300, 'Multiple Choices'],
  [301, 'Moved Permanently'],
  [302, 'Found'],
  [303, 'See Other'],
  [304, 'Not Modified'],
  [307, 'Temporary Redirect'],
  [308, 'Permanent Redirect'],
  [400, 'Bad Request'],
  [401, 'Unauthorized'],
  [402, 'Payment Required'],
  [403, 'Forbidden'],
  [404, 'Not Found'],
  [405, 'Method Not Allowed'],
  [406, 'Not Acceptable'],
  [407, 'Proxy Authentication Required'],
  [408, 'Request Timeout'],
  [409, 'Conflict'],
  [410, 'Gone'],
  [411, 'Length Required'],
  [412, 'Precondition Failed'],
  [413, 'Payload Too Large'],
  [414, 'URI Too Long'],
  [415, 'Unsupported Media Type'],
  [416, 'Range Not Satisfiable'],
  [417, 'Expectation Failed'],
  [419, 'Page Expired'],
  [420, 'Enhance Your Calm'],
  [421, 'Misdirected Request'],
  [422, 'Unprocessable Entity'],
  [423, 'Locked'],
  [424, 'Failed Dependency'],
  [425, 'Too Early'],
  [426, 'Upgrade Required'],
  [428, 'Precondition Required'],
  [429, 'Too Many Requests'],
  [430, 'Request Header Fields Too Large'],
  [431, 'Request Header Fields Too Large'],
  [450, 'Blocked By Windows Parental Controls'],
  [451, 'Unavailable For Legal Reasons'],
  [500, 'Internal Server Error'],
  [501, 'Not Implemented'],
  [502, 'Bad Gateway'],
  [503, 'Service Unavailable'],
  [504, 'Gateway Timeout'],
  [505, 'HTTP Version Not Supported'],
  [506, 'Variant Also Negotiates'],
  [507, 'Insufficient Storage'],
  [508, 'Loop Detected'],
  [509, 'Bandwidth Limit Exceeded'],
  [510, 'Not Extended'],
  [511, 'Network Authentication Required'],
]);

/**
 * Mock a POST request
 *
 * @summary Mocks a POST request to a url on the Holodeck server, returning a generated response with a 201 status, or
 * 204 when it has no body.
 */
export function POST(
  owner: object,
  url: string,
  response: ResponseGenerator,
  options?: Partial<Omit<Scaffold, 'response' | 'url' | 'method'>> & { RECORD?: boolean }
): Promise<void> {
  return mock(
    owner,
    {
      method: 'POST',
      url,
      scaffold: () => {
        const body = response();
        const status = options?.status ?? (body ? 201 : 204);

        return {
          status: status,
          statusText: options?.statusText ?? STATUS_TEXT_FOR.get(status) ?? '',
          headers: options?.headers ?? {},
          body: options?.body ?? null,
          method: 'POST',
          url,
          response: body,
        };
      },
    },
    options?.RECORD
  );
}

/**
 * mock a PUT request
 *
 * @summary Mocks a PUT request to a url on the Holodeck server, returning a generated response with a 200 status, or
 * 204 when it has no body.
 */
export function PUT(
  owner: object,
  url: string,
  response: ResponseGenerator,
  options?: Partial<Omit<Scaffold, 'response' | 'url' | 'method'>> & { RECORD?: boolean }
): Promise<void> {
  return mock(
    owner,
    {
      method: 'PUT',
      url,
      scaffold: () => {
        const body = response();
        const status = options?.status ?? (body ? 200 : 204);

        return {
          status: status,
          statusText: options?.statusText ?? STATUS_TEXT_FOR.get(status) ?? '',
          headers: options?.headers ?? {},
          body: options?.body ?? null,
          method: 'PUT',
          url,
          response: body,
        };
      },
    },
    options?.RECORD
  );
}
/**
 * mock a PATCH request
 *
 * @summary Mocks a PATCH request to a url on the Holodeck server, returning a generated response with a 200 status, or
 * 204 when it has no body.
 */
export function PATCH(
  owner: object,
  url: string,
  response: ResponseGenerator,
  options?: Partial<Omit<Scaffold, 'response' | 'url' | 'method'>> & { RECORD?: boolean }
): Promise<void> {
  return mock(
    owner,
    {
      method: 'PATCH',
      url,
      scaffold: () => {
        const body = response();
        const status = options?.status ?? (body ? 200 : 204);

        return {
          status: status,
          statusText: options?.statusText ?? STATUS_TEXT_FOR.get(status) ?? '',
          headers: options?.headers ?? {},
          body: options?.body ?? null,
          method: 'PATCH',
          url,
          response: body,
        };
      },
    },
    options?.RECORD
  );
}
/**
 * mock a DELETE request
 *
 * @summary Mocks a DELETE request to a url on the Holodeck server, returning a generated response with a 200 status, or
 * 204 when it has no body.
 */
export function DELETE(
  owner: object,
  url: string,
  response: ResponseGenerator,
  options?: Partial<Omit<Scaffold, 'response' | 'url' | 'method'>> & { RECORD?: boolean }
): Promise<void> {
  return mock(
    owner,
    {
      method: 'DELETE',
      url,
      scaffold: () => {
        const body = response();
        const status = options?.status ?? (body ? 200 : 204);

        return {
          status: status,
          statusText: options?.statusText ?? STATUS_TEXT_FOR.get(status) ?? '',
          headers: options?.headers ?? {},
          body: options?.body ?? null,
          method: 'DELETE',
          url,
          response: body,
        };
      },
    },
    options?.RECORD
  );
}

/**
 * Sets up Mocking for a HEAD request on the mock server
 * for the supplied url.
 *
 * The response body is generated by the supplied response function.
 *
 * Available options:
 * - status: the status code to return (default: 200)
 * - headers: the headers to return (default: {})
 * - body: the body to match against for the request (default: null)
 * - RECORD: record this request even when the suite is replaying, such as under CI (default: false).
 *   A local override for re-recording one request. Do not commit it; a committed RECORD means
 *   that request is never replayed against its fixture.
 *
 * @summary Mocks a HEAD request to a url on the Holodeck server, returning a generated response with a default 200
 * status.
 * @param url the url to mock, relative to the mock server host (e.g. `users/1`)
 * @param response a function which generates the response to return
 * @param options status, headers for the response, body to match against for the request, and whether to force recording
 * @return
 */
export function HEAD(
  owner: object,
  url: string,
  response: ResponseGenerator,
  // TODO: should we omit the `body` as well?
  // It does _seem_ possible for HEAD requests to have a body, but it should be ignored.
  // From MDN: Warning: If a response to a HEAD request has a body, the response body must be ignored.
  options?: Partial<Omit<Scaffold, 'response' | 'url' | 'method'>> & { RECORD?: boolean }
): Promise<void> {
  return mock(
    owner,
    {
      method: 'HEAD',
      url,
      scaffold: () => ({
        status: options?.status ?? 200,
        statusText: options?.statusText ?? 'OK',
        headers: options?.headers ?? {},
        body: options?.body ?? null,
        method: 'HEAD',
        url,
        response: response(),
      }),
    },
    options?.RECORD
  );
}
