// @embroider/config-meta-loader reads config off a <meta name="main-test-app/config/environment">
// tag that classic ember-cli's build injects via `{{content-for "head"}}`. That injection is done
// by @embroider/vite's `contentFor()` plugin, which reads a `.embroider/content-for.json` file
// generated by @embroider/compat's prebuild -- a step this app no longer runs. Without it, the meta
// tag never exists, `loadConfigFromMeta` silently returns an error *string* instead of throwing (see
// its implementation), and every config access below that (config.APP, config.rootURL, ...) becomes
// `undefined` rather than failing loudly -- which is why this was hard to spot: nothing crashes, but
// e.g. `Application.create(config.APP)` becomes `Application.create(undefined)`, silently falling
// back to Ember's default `rootElement` of `document.body` instead of `#ember-testing`, so rendering
// tests render into the wrong part of the page and every DOM assertion misses.
//
// Fixed by computing the same config directly instead of round-tripping through a meta tag. Keep
// this in sync with the environment-dependent branches this app actually needs.
const isProduction = import.meta.env.MODE === 'production';

export default {
  modulePrefix: 'main-test-app',
  podModulePrefix: 'main-test-app',
  environment: isProduction ? 'production' : 'test',
  rootURL: '/',
  locationType: isProduction ? 'history' : 'none',
  EmberENV: {
    RAISE_ON_DEPRECATION: false,
    _APPLICATION_TEMPLATE_WRAPPER: false,
    _TEMPLATE_ONLY_GLIMMER_COMPONENTS: true,
    _JQUERY_INTEGRATION: false,
  },
  APP: isProduction
    ? {}
    : {
        LOG_ACTIVE_GENERATION: false,
        LOG_VIEW_LOOKUPS: false,
        rootElement: '#ember-testing',
        autoboot: false,
      },
};
