name: DX

on:
  workflow_call:

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

permissions:
  contents: read
  actions: read

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/setup
        with:
          install: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Blueprints
        run: pnpm test:blueprints
