name: 'Check Deprecations'

on:
  workflow_dispatch:

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

jobs:
  test-all-deprecations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26.8.1
          cache: 'pnpm'
      - name: Install dependencies for main
        run: pnpm install
      - name: Basic Tests
        env:
          CI: true
          ASSERT_ALL_DEPRECATIONS: true
        run: pnpm test

  test-all-deprecations-releases:
    strategy:
      fail-fast: false
      matrix:
        scenario: [ember-beta, ember-canary]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26.8.1
          cache: 'pnpm'
      - name: Install dependencies for ${{ matrix.scenario }}
        run: pnpm install
      - name: Basic Tests
        env:
          CI: true
          ASSERT_ALL_DEPRECATIONS: true
        run: pnpm test:try-one ${{ matrix.scenario }} -- ember test --test-port=0
