name: 'Check Deprecations'

on:
  workflow_dispatch:

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

jobs:
  test-all-deprecations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          runtime: node@26.8.1
          cache: true
      - name: Basic Tests
        env:
          CI: true
          ASSERT_ALL_DEPRECATIONS: true
        run: pnpm test

  test-all-deprecations-releases:
    strategy:
      fail-fast: false
      matrix:
        scenario: [ember-beta, ember-canary]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          runtime: node@26.8.1
          cache: true
      - name: Basic Tests
        env:
          CI: true
          ASSERT_ALL_DEPRECATIONS: true
        run: pnpm test:try-one ${{ matrix.scenario }} -- ember test --test-port=0
